apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: openshift-pipelines-operator/overlays/stable
    repoURL: 'https://github.com/redhat-cop/gitops-catalog.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
